builders:
  bloom_filter_builder:
    import: 'package:bloom_filter_builder/bloom_filter_builder.dart'
    builder_factories:
      - 'bloomFilterBuilder'
    build_extensions: {'.txt': ['.g.dart']}
    auto_apply: root_package
    build_to: cache
    defaults:
      generate_for:
        include:
          - lib/**
