name: bloom_filter_builder
description: Tools for generating bloom filters at build time
version: 0.0.1
author: Aaron Madlon-Kay
homepage: https://github.com/amake/bloom_filter_builder

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.2.2
  dart_style: ^1.3.3
  args: ^1.5.2
  bloom_filter:
    git:
      url: https://github.com/amake/bloom_filter.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
